In [10]:
import numpy as np

In [25]:
X = np.array([[1, 2, 3],
             [4, 5, 6]])
y = np.array([1])
w = np.array([9, 8, 7])

for x, y in zip(X, y):
    print(x, y)

p = np.dot(X, w)
print(p)
a = np.array([101])
print(X.ravel(), y.ravel().shape)

[1 2 3] 1
[ 46 118]
[1 2 3 4 5 6] (1,)


In [18]:
np.where(a >= 100, 1, 0)

array([1])

In [6]:
rgen = np.random.RandomState(1)
w = rgen.normal(0.0, 0.01, 2)
rgen.permutation(100)

array([62, 40, 39, 69, 37, 38, 51, 85, 65, 54, 97, 80, 98, 48, 32, 87, 36,
       67, 17, 91, 31, 81, 82, 33, 56, 83, 55, 66, 35, 10,  2, 46, 96, 19,
       27, 42, 59, 77, 73, 44, 53, 92, 23, 34, 89, 58, 70, 15, 86, 41, 45,
       94, 52, 26, 12, 43, 74, 24,  4, 95, 72, 49, 21, 90,  3, 30, 47, 78,
        8, 60,  0, 93, 57, 22, 61, 63,  7, 99, 13, 68, 88, 14, 29, 28, 11,
       84, 18, 20, 50, 25,  6, 71, 76,  1, 16, 64, 79,  5, 75,  9])

In [5]:
w += 10
w

array([10.01624345,  9.99388244])

In [6]:
int(1)

1