In [1]:
import numpy as np

<h3>Artificial Neuron</h3> 
An artificial neuron is defined as a binary classifier. It takes the linear combination (z) of its inputs (x<sub>i</sub>), each multiplied by some weights (w<sub>i</sub>), and outputs 1 if it's greater than some threshold (θ) and 0 otherwise <br>
z = x<sub>1</sub>w<sub>1</sub> + x<sub>2</sub>w<sub>2</sub> + ........ x<sub>n</sub>w<sub>n</sub> and <br>
**FINISH**

In [2]:
X = np.array([[1, 2, 3],
             [4, 5, 6]])
y = np.array([0, 1])
w = np.array([9, 8, 7])

for x, y in zip(X, y):
    print(x, y)

p = np.dot(X, w)
print(p)
a = np.array([101])

[1 2 3] 0
[4 5 6] 1
[ 46 118]


In [3]:
np.where(a >= 100, 1, 0)

array([1])

In [5]:
rgen = np.random.RandomState(1)
w = rgen.normal(0.0, 0.01, 2)
w, w.shape

(array([ 0.01624345, -0.00611756]), (2,))

In [5]:
w += 10
w

array([10.01624345,  9.99388244])

In [6]:
int(1)

1